project:
  type: website

website:

  title: "Christian Stankov"
  
  site-url: https://chrisenv.github.io/
  description: "Christian Stankov's personal website"
  
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: content/blog.qmd
        text: blog
      - href: content/cv.qmd
        text: cv
    
    right:
      - icon: github
        href: https://github.com/ChrisEnv/chrisenv.github.io
        aria-label: GitHub repo
      - icon: linkedin
        href: https://linkedin.com/in/christian-stankov
        aria-label: LinkedIn
format:
  html:
    theme: cosmo
    css: "/resources/css/styles.css"
    toc: true

execute:
  freeze: false
  
editor: source

